name: hostelite
description: A hostel management app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  add_2_calendar: ^2.1.0
  table_calendar: ^3.0.6
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  provider: ^6.0.3
  image_picker: ^1.0.4
  flutter_spinkit: ^5.0.0
  geolocator: ^10.1.0
  firebase_messaging: ^14.6.9
  shared_preferences: ^2.0.11
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/H.jpg
    - assets/
    - assets/H_of_Hostelite.jpg
    - assets/ostellite.png
    - assets/Your Hostel Companion.png
    - assets/Group 33653.png
    - assets/Rectangle 368.png
    - assets/home_Screen_Student/2720490 1.png
    - assets/home_Screen_Student/bermuda-747 1.png
    - assets/home_Screen_Student/Group 33636.png
    - assets/home_Screen_Student/sign-in-4 1.png
    - assets/create_account_page/Arrow - Left.png
    - assets/create_account_page/Create Account.png
    - assets/create_account_page/Get your home here!.png
    - assets/create_account_page/Vector.png
    - assets/h_of_hostel/Rectangle 208.png
    - assets/h_of_hostel/Rectangle 209.png
    - assets/h_of_hostel/Rectangle 210.png
    - assets/h_of_hostel/Rectangle 211.png
    - assets/h_of_hostel/Rectangle 213.png
    - assets/h_of_hostel/Rectangle 214.png
    - assets/h_of_hostel/Rectangle 215.png
    - assets/h_of_hostel/Rectangle 216.png
    - assets/h_of_hostel/Rectangle 217.png
    - assets/h_of_hostel/Rectangle 218.png
    - assets/second_page/Contact to authorities whenever you have any complaints..png
    - assets/second_page/Group 33655.png
    - assets/second_page/Group 33694.png
    - assets/second_page/Solve your Issues.png
    - assets/third_page/Fast & Easy!.png
    - assets/third_page/Group 33656.png
    - assets/third_page/Now you can mark your entry and exit in just a tap..png
    - assets/third_page/undraw_fast_loading_0lbh 2.png
    - assets/fourth_page/get_started/Get Started.png
    - assets/fourth_page/get_started/Rectangle 425.png
    - assets/fourth_page/Group 33657.png
    - assets/fourth_page/Keep Track!.png
    - assets/fourth_page/Now keep track of hostelites with our enhanced location tracker ..png
    - assets/fourth_page/undraw_Account_re_o7id 1.png

   #  - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
